repo: netlifydemo/netlify-home
branch: master
collections:
  - slug: "post"
    label: "Blog Post"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", class: "post-title"}
      - {label: "Author", name: "author", widget: "string", preview: "author", tagname: "p", class: "post-meta"}
      - {label: "Cover Image", name: "image", widget: "image", tagname: "div", class: "post-img", folder: "img/posts"}
      - {label: "Post Body", name: "body", widget: "markdown", tagname: "div", class: "post-bd"}
      - {label: "Short Title", name: "short_title", widget: "string", tagname: "h1", class: "blurb-title"}
      - {label: "Description", name: "description", widget: "string", tagname: "p", class: "small muted"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", tagname: "div", class: "media-img optional", folder: "img/posts/thumbnails"}
      - {label: "Tags", name: "tags", widget: "tags"}
  - slug: "docs"
    label: "Doc Pages"
    folder: "_docs"
    create: true
    fields:
      - {label: "Menu Title", name: "title", widget: "string", tagname: "h4", class: "doc-title"}
      - {label: "Position", name: "position", widget: "number", tagname: "div", class: "doc-position"}
      - {label: "Post Body", name: "body", widget: "markdown", tagname: "div", class: "post-bd"}
